name: tests

on: 
  workflow_dispatch:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile
        run: make all

      - name: merge testing branch
        run: git merge testing

      - name: test
        run: ./tests.sh